### ISSUE TITLE
yarn dev error

### ISSUE THREAD

**Issue by eaorak** [taniarascia/taniarascia.com#132]
First of all thanks so much for sharing your experiences regarding migrating from Wordpress. I'm trying to do the same and I thought it would be nice to start with your project rather than the advanced starter.

I cloned the repo and ran `yarn dev` locally. It starts with this error and gives many other GraphQL errors.

```

ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "allMarkdownRemark" on type "Query".

If you don't expect "allMarkdownRemark" to exist on the type "Query" it is most likely a typo.
However, if you expect "allMarkdownRemark" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "allMarkdownRemark" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: gatsby-node.js:105:10

[ { GraphQLError: Cannot query field "allMarkdownRemark" on type "Query".
      at Object.Field (taniarascia.com/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:53:31)
      at Object.enter (taniarascia.com/node_modules/graphql/language/visitor.js:324:29)
      at Object.enter (taniarascia.com/node_modules/graphql/language/visitor.js:375:25)
      at visit (taniarascia.com/node_modules/graphql/language/visitor.js:242:26)
      at validate (taniarascia.com/node_modules/graphql/validation/validate.js:73:24)
      at GraphQLRunner.validate (taniarascia.com/node_modules/gatsby/dist/query/graphql-runner.js:58:22)
      at GraphQLRunner.query (taniarascia.com/node_modules/gatsby/dist/query/graphql-runner.js:82:25)
      at taniarascia.com/node_modules/gatsby/dist/bootstrap/graphql-runner.js:21:37
      at Promise (taniarascia.com/gatsby-node.js:112:7)
      at new Promise (<anonymous>)
      at Object.exports.createPages (taniarascia.com/gatsby-node.js:105:10)
      at runAPI (taniarascia.com/node_modules/gatsby/dist/utils/api-runner-node.js:248:37)
      at resolve (taniarascia.com/node_modules/gatsby/dist/utils/api-runner-node.js:367:15)
      at Promise._execute (taniarascia.com/node_modules/bluebird/js/release/debuggability.js:384:9)
      at Promise._resolveFromExecutor (taniarascia.com/node_modules/bluebird/js/release/promise.js:518:18)
      at new Promise (taniarascia.com/node_modules/bluebird/js/release/promise.js:103:10)
    message: 'Cannot query field "allMarkdownRemark" on type "Query".',
    locations: [ [Object] ] } ]
```

And also many of these:

```
ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '../../content/images/codrops.png' in 'taniarascia.com/src/pages'

File:
```

Any ideas?

**Comment by taniarascia** [comment]
Glad you like the site! The content of the site isn't publicly available in the repo, so it fails looking for it. I don't provide any support for cloning this repo, though.
